name: Build, Upload and Deploy WordPress

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    
    - name: Checkout code
      uses: actions/checkout@v2

    
    # Step 2: Set up AWS CLI (for uploading to S3 and EC2 deployment)
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  

    
    - name: Create tarball
      run: |
        sudo mkdir /home/runner/work/maged
        sudo cp -r /home/runner/work/WordPress/WordPress/* /home/runner/work/maged
        cd /home/runner/work/maged
        sudo tar -czvf app_2024-12-23_20-21.tar.gz *
      
    - name: Upload tarball to S3
      run: |
       
        S3_BUCKET="s3://maged-bucket"  # Specify your S3 bucket name
        aws s3 mv s3://maged-bucket/ s3://maged-bucket-old/ --recursive
        aws s3 cp /home/runner/work/maged/app_2024-12-23_20-21.tar.gz s3://maged-bucket/  

