name: Build, Upload and Deploy WordPress

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS CLI (for uploading to S3 and EC2 deployment)
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Specify the AWS region

    # Step 3: Install git and create tarball
    - name: Create tarball
      run: |
        DATE=$(date +%Y-%m-%d)
        TAR_FILE="app_$DATE.tar.gz"
        
        # Clone the repository or pull latest changes
        cd /tmp
        git clone https://github.com/Maged2344/WordPress.git
        cd WordPress

        # Create tarball with the current date
        tar -czvf /tmp/$TAR_FILE *
      
    # Step 4: Upload tarball to S3
    - name: Upload tarball to S3
      run: |
        DATE=$(date +%Y-%m-%d)
        TAR_FILE="/tmp/app_$DATE.tar.gz"
        S3_BUCKET="s3://maged-bucket"  # Specify your S3 bucket name
        
        # Upload the tarball to S3
        aws s3 cp $TAR_FILE $S3_BUCKET/
