name: Build, Upload and Deploy WordPress

on:
  push:
    branches:
      - master  # Trigger workflow when code is pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    
    # Step 2: Set up AWS CLI (for uploading to S3 and EC2 deployment)
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Specify the AWS region

    
    - name: Create tarball
      run: |
        # DATE=$(date +"%Y-%m-%d_%H-%M")
     
        mkdir /home/runner/work/wordpress
        cp -r /home/runner/work/WordPress/WordPress/* /home/runner/work/wordpress
        cd /home/runner/work/wordpress
        tar -czvf app_2024-12-23_20-21.tar.gz .
      

    - name: Upload tarball to S3
      run: |
       
        TAR_FILE="app_$DATE.tar.gz"
        S3_BUCKET="s3://maged-bucket"  # Specify your S3 bucket name
        aws s3 mv s3://maged-bucket/ s3://maged-bucket-old/ --recursive
        
        # Upload the tarball to S3
        aws s3 cp app_2024-12-23_20-21.tar.gz s3://maged-bucket/  

